function ConvertTo-NBRackHTML {
<#
    .SYNOPSIS
        Convert rack elevation data to HTML format

    .DESCRIPTION
        Internal helper function that generates a standalone HTML page
        representing a rack elevation diagram.

    .PARAMETER RackName
        Display name of the rack

    .PARAMETER SiteName
        Display name of the site

    .PARAMETER UHeight
        Total height of the rack in U

    .PARAMETER Face
        Face being displayed (Front or Rear)

    .PARAMETER ElevationData
        Array of elevation unit objects from Get-NBDCIMRackElevation

    .PARAMETER SvgContent
        Optional SVG content to embed (when using native renderer)
#>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$RackName,

        [string]$SiteName = '',

        [int]$UHeight = 42,

        [string]$Face = 'Front',

        [PSCustomObject[]]$ElevationData,

        [string]$SvgContent
    )

    # If SVG content provided, embed it
    if ($SvgContent) {
        return @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$RackName - $Face Face | $SiteName</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 20px;
            background: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 { margin: 0 0 10px; font-size: 1.5em; }
        .meta { color: #666; margin-bottom: 20px; }
        .svg-container { text-align: center; }
        svg { max-width: 100%; height: auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>$RackName - $Face Face</h1>
        <p class="meta">Site: $SiteName | Height: ${UHeight}U</p>
        <div class="svg-container">
            $SvgContent
        </div>
    </div>
    <footer style="text-align:center;color:#999;margin-top:20px;font-size:0.8em;">
        Generated by PowerNetbox | $(Get-Date -Format 'yyyy-MM-dd HH:mm')
    </footer>
</body>
</html>
"@
    }

    # Build HTML table from elevation data
    $tableRows = [System.Text.StringBuilder]::new()

    # Create a lookup of devices by position
    $deviceLookup = @{}
    foreach ($unit in $ElevationData) {
        if ($unit.device) {
            $deviceLookup[[int]$unit.id] = $unit
        }
    }

    # Generate rows from top to bottom
    for ($u = $UHeight; $u -ge 1; $u--) {
        $unit = $deviceLookup[$u]

        if ($unit -and $unit.device) {
            $deviceName = $unit.device.display
            $deviceDesc = if ($unit.device.description) { $unit.device.description } else { '' }

            [void]$tableRows.AppendLine(@"
        <tr class="occupied">
            <td class="u-num">$u</td>
            <td class="device" title="$deviceDesc">
                <span class="device-name">$deviceName</span>
            </td>
        </tr>
"@)
        }
        else {
            [void]$tableRows.AppendLine(@"
        <tr class="empty">
            <td class="u-num">$u</td>
            <td class="slot"></td>
        </tr>
"@)
        }
    }

    return @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$RackName - $Face Face | $SiteName</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 20px;
            background: #f5f5f5;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 { margin: 0 0 10px; font-size: 1.5em; }
        .meta { color: #666; margin-bottom: 20px; }
        .rack-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9em;
        }
        .rack-table th {
            background: #333;
            color: white;
            padding: 8px;
            text-align: left;
        }
        .rack-table td {
            border: 1px solid #ddd;
            padding: 6px 10px;
        }
        .u-num {
            width: 40px;
            text-align: center;
            font-weight: bold;
            background: #f0f0f0;
            color: #666;
        }
        .slot {
            background: #fafafa;
            min-height: 20px;
        }
        .occupied .slot, .occupied .device {
            background: #e3f2fd;
        }
        .device-name {
            font-weight: 500;
            color: #1976d2;
        }
        tr.empty {
            opacity: 0.5;
        }
        tr.occupied {
            opacity: 1;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>$RackName - $Face Face</h1>
        <p class="meta">Site: $SiteName | Height: ${UHeight}U</p>
        <table class="rack-table">
            <thead>
                <tr>
                    <th>U#</th>
                    <th>Device</th>
                </tr>
            </thead>
            <tbody>
$($tableRows.ToString())
            </tbody>
        </table>
    </div>
    <footer style="text-align:center;color:#999;margin-top:20px;font-size:0.8em;">
        Generated by PowerNetbox | $(Get-Date -Format 'yyyy-MM-dd HH:mm')
    </footer>
</body>
</html>
"@
}
